// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVO5pvjNig_HvEH1HJZMRX7Yy7LWyU-lc',
    appId: '1:21729909661:web:75cb551b1797de3c91ad74',
    messagingSenderId: '21729909661',
    projectId: 'skincareapp-2f01f',
    authDomain: 'skincareapp-2f01f.firebaseapp.com',
    storageBucket: 'skincareapp-2f01f.firebasestorage.app',
    measurementId: 'G-MTKQDDN7P8',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAawDTWXTrUDgGMcWzng4fV6Zpt_c--pI',
    appId: '1:21729909661:android:ba2b523a6c374f6291ad74',
    messagingSenderId: '21729909661',
    projectId: 'skincareapp-2f01f',
    storageBucket: 'skincareapp-2f01f.firebasestorage.app',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5-VN4GNwVE6LgPZfVD1A-Lu4E0wvNWmc',
    appId: '1:21729909661:ios:42ade3f83caa8e3091ad74',
    messagingSenderId: '21729909661',
    projectId: 'skincareapp-2f01f',
    storageBucket: 'skincareapp-2f01f.firebasestorage.app',
    iosBundleId: 'com.example.skinCare',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5-VN4GNwVE6LgPZfVD1A-Lu4E0wvNWmc',
    appId: '1:21729909661:ios:42ade3f83caa8e3091ad74',
    messagingSenderId: '21729909661',
    projectId: 'skincareapp-2f01f',
    storageBucket: 'skincareapp-2f01f.firebasestorage.app',
    iosBundleId: 'com.example.skinCare',
  );

  static  FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVO5pvjNig_HvEH1HJZMRX7Yy7LWyU-lc',
    appId: '1:21729909661:web:ac107aeb8b2efce691ad74',
    messagingSenderId: '21729909661',
    projectId: 'skincareapp-2f01f',
    authDomain: 'skincareapp-2f01f.firebaseapp.com',
    storageBucket: 'skincareapp-2f01f.firebasestorage.app',
    measurementId: 'G-67S5TCGDH4',
  );
}
